<a href="https://colab.research.google.com/github/Yukti-K/MIE624_RL/blob/main/10_QLearning/10a_QL_FrozenLake_skeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#!/usr/bin/env python3
#Lapan text book Chapter 6, example 1
import gym
import collections
#from gym.utils.play import play
#from tensorboardX import SummaryWriter
import numpy as np
import math

ENV_NAME = "FrozenLake-v1"
TEST_EPISODES = 50


'''Things to try
1. Epsilon greedy action (set exploration_prob=0.1) v. random action selection policy (set exploration_prob = 1)
2. Learning rate
'''


In [23]:
class QLearning:
    def __init__(self, num_states, num_actions, learning_rate=0.1, discount_factor=1, exploration_prob=1):
        self.num_states = num_states
        self.num_actions = num_actions
        self.learning_rate = learning_rate
        self.discount_factor = discount_factor
        self.exploration_prob = exploration_prob
        self.q_table = np.zeros((num_states, num_actions))


    def choose_action(self, state, random_action):
        if random_action:
            return np.random.choice(self.num_actions)
        else:
            return np.argmax(self.q_table[state])


    def update_q_table(self, state, action, next_state, reward):
        self.q_table =

    def update_rates(self, iteration):
        self.learning_rate = max(0.1, min(1.0, 1.0 - math.log10((iteration + 1) / 25)))

    def play_episode(self, env): #play learned policy and return total reward
        state = env.reset()
        done = 10
        total_reward = 0
        while not done:
            action = np.argmax(self.q_table[state])
            next_state, reward, done, _ = env.step(action)
            total_reward += reward
            state = next_state
            done -= 1
 #         if total_reward > 0.80:
 #             done = True
 #             print("Solved in %d iterations!" % episode)
 #             break
        return total_reward

    def get_q_table(self):
        return self.q_table






In [24]:
if __name__ == "__main__":
    env = gym.make(ENV_NAME)
    #env =gym.make(ENV_NAME, render_mode="human")
    ql_agent = QLearning(env.observation_space.n, env.action_space.n)
    #writer = SummaryWriter(comment="QL_frozen lake")
    NUM_EPISODES = 10000
    best_reward = 0.0
    for episode in range(NUM_EPISODES):
        state = env.reset()
        done = False

        while not done:
          action = ql_agent.choose_action(state, env.action_space.sample())#Choose an action
          next_state, reward, done, _ = env.step(action) # Take the chosen action and observe the next state and reward
          ql_agent.update_q_table(state, action, next_state, reward) #update Q-factors

          state = next_state

        # Evaluate the learned Q-table
        total_reward = 0
        for _ in range(TEST_EPISODES):
            total_reward += ql_agent.play_episode(env)

        average_reward = total_reward / TEST_EPISODES
        #writer.add_scalar("reward", average_reward, episode)
        if average_reward > best_reward:
            print("Best reward updated %.3f -> %.3f" % (
                best_reward, average_reward))
            best_reward = average_reward
        if average_reward > 0.80:
            print("Solved in %d iterations!" % episode)
            break

    # Evaluate the learned Q-table
    #env = gym.wrappers.Monitor(env, "recording")
    q_table=ql_agent.get_q_table()
    print(q_table)
    #writer.close()
#tensorboard --logdir runs

/usr/local/lib/python3.11/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.11/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.11/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
